export const TOKEN_KEY = 'gramshop.token'
export const USER_KEY = 'gramshop.user'
export const STORE_KEY = 'gramshop.storeId'
export const SIDEBAR_COLLAPSED_KEY = 'gramshop.sidebarCollapsed'
export const SHOP_TOKEN_KEY = 'gramshop.shop.token'
export const SHOP_USER_KEY = 'gramshop.shop.user'
export const SHOP_CART_KEY = 'gramshop.shop.cart'
