export const queryKeys = {
  me: ['auth', 'me'] as const,
  dashboard: (storeId?: number | null) => ['dashboard', storeId ?? 'all'] as const,
  stores: ['stores'] as const,
  store: (id: number) => ['stores', id] as const,
  users: (q: unknown) => ['users', q] as const,
  user: (id: number) => ['users', id] as const,
  categories: ['categories'] as const,
  products: (q: unknown) => ['products', q] as const,
  product: (id: number, storeId?: number | null) => ['products', id, storeId ?? 'any'] as const,
  productSearch: (query: string, storeId?: number | null) => ['products', 'search', query, storeId ?? 'any'] as const,
  inventory: (q: unknown) => ['inventory', q] as const,
  inventoryLedger: (q: unknown) => ['inventory', 'ledger', q] as const,
  lowStock: (storeId?: number | null) => ['inventory', 'low-stock', storeId ?? 'all'] as const,
  purchases: (q: unknown) => ['purchases', q] as const,
  purchase: (id: number) => ['purchases', id] as const,
  bills: (q: unknown) => ['bills', q] as const,
  bill: (id: number) => ['bills', id] as const,
  invoice: (id: number) => ['bills', id, 'invoice'] as const,
  heldBills: (storeId?: number | null) => ['pos', 'held', storeId ?? 'all'] as const,
  returns: (q: unknown) => ['returns', q] as const,
  return: (id: number) => ['returns', id] as const,
  customers: (q: unknown) => ['customers', q] as const,
  customer: (id: number) => ['customers', id] as const,
  customerSearch: (query: string, storeId?: number | null) => ['customers', 'search', query, storeId ?? 'any'] as const,
  customerHistory: (id: number) => ['customers', id, 'history'] as const,
  customerLedger: (id: number, q: unknown) => ['customers', id, 'ledger', q] as const,
  customerPayments: (id: number) => ['customers', id, 'payments'] as const,
  customerWallet: (id: number) => ['customers', id, 'wallet'] as const,
  referrals: (q: unknown) => ['referrals', q] as const,
  reports: (name: string, q: unknown) => ['reports', name, q] as const,
  settings: ['settings'] as const,
  audit: (q: unknown) => ['audit', q] as const,
}
